name: Release

on:
  release:
    types: [published]

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Zip Files
        uses: vimtor/action-zip@v1.2
        with:
          files: src/**
          dest: dist/Arachnophobia.zip
      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/Arachnophobia.zip'
          repo-token: ${{ secrets.TOKEN_GITHUB }}
      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH }}
          project: S0jHcAjs
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            minecraft
          game-versions: |-
            1.12.x
            1.16.x
            1.17.x
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: dist/Arachnophobia.zip